# Generated by Django 5.0.4 on 2024-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='active_patient_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemail', models.EmailField(max_length=35)),
                ('pphone', models.CharField(max_length=12)),
                ('DID', models.CharField(max_length=8)),
                ('RID', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='disease_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeID', models.CharField(max_length=8)),
                ('DName', models.CharField(max_length=30)),
                ('DImage', models.FileField(default=None, max_length=250, null=True, upload_to='media/patient/')),
            ],
        ),
        migrations.CreateModel(
            name='patient_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_number', models.CharField(max_length=11, unique=True)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('contact', models.CharField(max_length=12)),
                ('econtact', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='media/patient/')),
            ],
        ),
        migrations.CreateModel(
            name='patient_list_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('email', models.EmailField(max_length=35)),
                ('contact', models.CharField(max_length=12)),
                ('econtact', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='media/patient/')),
            ],
        ),
    ]
