# Generated by Django 5.0.4 on 2024-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_patient_list',
            name='Date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='active_patient_list',
            name='PID',
            field=models.CharField(default=None, max_length=11, null=True, unique=True),
        ),
    ]
