# Generated by Django 5.0.4 on 2024-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_active_patient_list_date_active_patient_list_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_patient_list',
            name='PID',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
