# Generated by Django 5.0.4 on 2024-05-19 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteExercise2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.CharField(max_length=100)),
                ('DID', models.CharField(default=None, max_length=100, null=True)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('created_date', models.DateField()),
                ('created_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notificationes2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RID', models.CharField(max_length=100)),
                ('DID', models.CharField(default=None, max_length=100, null=True)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('created_date', models.DateField()),
                ('created_time', models.TimeField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=100)),
                ('eid', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('video_duration', models.FloatField()),
                ('time', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient_list')),
            ],
        ),
    ]
