# Generated by Django 5.0.4 on 2024-05-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='media/patient/')),
            ],
        ),
    ]
