# Generated by Django 5.0.4 on 2024-05-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_list',
            name='gender',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
