# Generated by Django 5.0.4 on 2024-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_admin_list_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_list',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/Admin/'),
        ),
    ]
