# Generated by Django 5.0.4 on 2024-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_number', models.CharField(blank=True, max_length=8, unique=True)),
                ('title', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('ltitle', models.CharField(default='(PT)', editable=False, max_length=5)),
                ('gender', models.CharField(max_length=6)),
                ('NIDP_number', models.CharField(max_length=18)),
                ('BPA_number', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=12)),
                ('ephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('ch_name', models.CharField(blank=True, max_length=100)),
                ('division', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='doctor/')),
                ('active', models.CharField(default='no', max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_list_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('ltitle', models.CharField(default='(PT)', editable=False, max_length=5)),
                ('gender', models.CharField(max_length=6)),
                ('NIDP_number', models.CharField(max_length=18)),
                ('BPA_number', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=12)),
                ('ephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=35)),
                ('password', models.CharField(max_length=30)),
                ('ch_name', models.CharField(blank=True, max_length=100)),
                ('division', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='doctor/')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_patient_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DID', models.CharField(max_length=8)),
                ('RID', models.CharField(max_length=15)),
                ('PName', models.CharField(max_length=25)),
                ('PDisease', models.CharField(max_length=30)),
                ('PAge', models.IntegerField()),
                ('PPhone', models.CharField(max_length=12)),
                ('PEmail', models.CharField(max_length=35)),
                ('PExercise', models.CharField(max_length=100)),
                ('PDcategory', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDeactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DID', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='exercise_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.CharField(max_length=30)),
                ('EName', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, max_length=250, null=True, upload_to='exercise/')),
                ('video', models.FileField(default=None, max_length=250, null=True, upload_to='exercise/videos/')),
            ],
        ),
    ]
