# Generated by Django 5.0.4 on 2024-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_patient_list',
            name='Date',
            field=models.DateField(default=None, null=True),
        ),
    ]
