# Generated by Django 5.0.4 on 2024-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_patient_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_patient_list',
            name='alDID',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
